sudo: required
language: generic
os:
  - linux
dist: trusty

before_install: |
  sudo curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
  export PATH="~/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
  pyenv --help
  pyenv install 3.6.0
  pyenv virtualenv 3.6.0 general
  pyenv global general

script:
  - python3 --version
