sudo: required
language: generic
os:
  - linux
dist: trusty

script: |
  sudo curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
  export PATH="~/.pyenv/bin:$PATH"
  pyenv init -
